In [2]:
!uv pip install matplotlib

Audited 1 package in 7ms


In [ ]:
import numpy as np 

In [ ]:
input =np.array([[0,1,2,3],[1,2,3,4],[2,3,4,5]])
weight = np.array([[0.2,0.1,0.3,0.5],[0.0,0.1,0.2,0.3],[0.3,0.4,0.5,0.6]])
bias = [4,3,5,8]

layer1 = np.dot(input,weight.T)
print(layer1)
layer2 = np.dot(layer1,weight)
print(layer2)


[[2.2 1.4 3.2]
 [3.3 2.  5. ]
 [4.4 2.6 6.8]]
[[1.4  1.64 2.54 3.44]
 [2.16 2.53 3.89 5.25]
 [2.92 3.42 5.24 7.06]]


In [16]:
import numpy as np
X = [[0,1,2,3],
     [1,2,3,4],
     [2,3,4,5]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        np.random.seed(42)
        self.weights = 0.10 * np.random.rand(n_inputs,n_neurons) 
        self.biases = np.zeros((1,n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
# print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)


[[0.04355258 0.06481855]
 [0.07673453 0.11551981]
 [0.10991647 0.16622106]]
