In [28]:
import numpy as np

In [29]:
print(np.array(([1,2,3],[4,5,6],[7,8,9])))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
zeros = np.zeros((3,3)) 
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
randoms = np.random.rand(2,3)
randoms

array([[0.76355076, 0.85438912, 0.38798776],
       [0.8412943 , 0.47486049, 0.66168445]])

In [32]:
randoms.shape

(2, 3)

In [33]:
randoms.ndim

2

In [34]:
randoms.size

6

In [35]:
randoms.dtype

dtype('float64')

# MATRIX OPERATION

In [36]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [37]:
B = np.array([[5,6], [7,8]])
B

array([[5, 6],
       [7, 8]])

In [38]:
np.dot(A,B) ## matrix multiplication

array([[19, 22],
       [43, 50]])

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [40]:
print(a-b)

[-3 -3 -3]


In [41]:
print(A-B)

[[-4 -4]
 [-4 -4]]


In [42]:
print(np.transpose(A)) 

[[1 3]
 [2 4]]


In [43]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [45]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [49]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

w = np.zeros(X.shape[1]) 
X[0]

array([0, 0])

In [ ]:
w = np.array([[1], [2]])   # shape (2,1)
x = np.array([[3], [4]])   # shape (2,1)

print(w.T @ x)             # matrix multiply w.T => will transpose the matrix @ is for matrix multiply 


[[11]]
