In [2]:
import torch

In [3]:
# Scalar
x = torch.tensor(5)
print(x)     

tensor(5)


In [4]:
# Vector
v = torch.tensor([1, 2, 3])
print(v) 

tensor([1, 2, 3])


In [5]:
# Matrix
m = torch.tensor([[1, 2], [3, 4]])
print(m)


tensor([[1, 2],
        [3, 4]])


In [6]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(a + b)    # element-wise add
print(a * b)    # element-wise multiply
print(torch.dot(a, b))   # dot product
print(a.mean()) # mean


tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)
tensor(2.)


In [7]:
# Check if GPU is available
# print(torch.cuda.is_available())

# Move tensor to GPU
# x = torch.tensor([1, 2, 3], device="cuda")
# print(x)


In [8]:
x = torch.tensor(2.0, requires_grad=True)  # “Track all operations on this tensor because I’ll need gradients w.r.t. it later.”

y = x**2 + 3*x + 5   # function

y.backward()         # compute dy/dx
print(x.grad)        # prints tensor(7.)

tensor(7.)


In [9]:
import torch.nn as nn
import torch.optim as optim

In [10]:
# Simple model: input -> hidden -> output
model = nn.Sequential(
    nn.Linear(1, 10),   # 1 input → 10 hidden neurons
    nn.ReLU(),          # activation
    nn.Linear(10, 1)    # 10 → 1 output
)


In [11]:
# Loss function
loss_fn = nn.MSELoss()

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [12]:
for epoch in range(100):
    # Forward pass
    y_pred = model(torch.tensor([[1.0]]))  # example input

    # Compute loss
    y_true = torch.tensor([[2.0]])         # example target
    loss = loss_fn(y_pred, y_true)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(epoch, loss.item())


0 4.081465244293213
10 0.5311488509178162
20 0.05094873160123825
30 0.004030545242130756
40 0.0002957413671538234
50 2.123728336300701e-05
60 1.5158375390456058e-06
70 1.0801740302213148e-07
80 7.677058988520002e-09
90 5.403677505455562e-10
