In [2]:
import torch

In [3]:
# Scalar
x = torch.tensor(5)
print(x)     

tensor(5)


In [4]:
# Vector
v = torch.tensor([1, 2, 3])
print(v) 

tensor([1, 2, 3])


In [5]:
# Matrix
m = torch.tensor([[1, 2], [3, 4]])
print(m)


tensor([[1, 2],
        [3, 4]])


In [6]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(a + b)    # element-wise add
print(a * b)    # element-wise multiply
print(torch.dot(a, b))   # dot product
print(a.mean()) # mean


tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)
tensor(2.)


In [ ]:
# Check if GPU is available
# print(torch.cuda.is_available())

# Move tensor to GPU
# x = torch.tensor([1, 2, 3], device="cuda")
# print(x)


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
x = torch.tensor(2.0, requires_grad=True)  # “Track all operations on this tensor because I’ll need gradients w.r.t. it later.”

y = x**2 + 3*x + 5   # function

y.backward()         # compute dy/dx
print(x.grad)        # prints tensor(7.)

tensor(7.)


In [ ]:
import torch.nn as nn
import torch.optim as optim

In [12]:
# Simple model: input -> hidden -> output
model = nn.Sequential(
    nn.Linear(1, 10),   # 1 input → 10 hidden neurons
    nn.ReLU(),          # activation
    nn.Linear(10, 1)    # 10 → 1 output
)


In [ ]:
# Loss function
loss_fn = nn.MSELoss()

# Optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [18]:
for epoch in range(100):
    # Forward pass
    y_pred = model(torch.tensor([[1.0]]))  # example input

    # Compute loss
    y_true = torch.tensor([[2.0]])         # example target
    loss = loss_fn(y_pred, y_true)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(epoch, loss.item())


0 5.571223482547794e-10
10 4.780531526193954e-11
20 4.604316927725449e-12
30 5.115907697472721e-13
40 5.115907697472721e-13
50 5.115907697472721e-13
60 5.115907697472721e-13
70 5.115907697472721e-13
80 2.2737367544323206e-13
90 2.2737367544323206e-13
